version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: vinitvers
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file: .env
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "dev"]

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: ["npm", "start"]

volumes:
  db_data:
